### ISSUE TITLE
[JEExplorer] Modification du css du core pour la prise en compte du css du menu

### ISSUE THREAD

**Issue by lucguinchard** [NextDom/nextdom-core#1701]
> Avant de commencé je veux rappeler que JEExplorer est disponible que pour Jeedom v4. Je suppose que cela est du à l'évolution de la feuille de style en V4.

Voici la présentation sur un JEEDOM v4 (light version) :
![image](https://user-images.githubusercontent.com/17431299/74637013-71bf4d80-5169-11ea-87be-046bf0155127.png)

Voici les la présentation actuel sur nextdom (0.6.8 : light version)
![image](https://user-images.githubusercontent.com/17431299/74637575-83552500-516a-11ea-8809-8686448d28f8.png)

Après certaines modifications :

```css
.elfinder .ui-widget-content {
    background-color: #546e7a !important;
}
.elfinder-dialog .ui-dialog-titlebar {
    background-color: rgb(85,85,85) !important;
}
.elfinder .elfinder-button {
    width: 20px;
}
.elfinder .elfinder-button:hover {
    background: rgb(85, 85, 85);
}
.ui-helper-hidden-accessible {
    padding: 0 !important;
    width: 0 !important;
}
.elfinder .elfinder-button-search input {
    border: 0 !important;
}
```
Voici le résultat :

![image](https://user-images.githubusercontent.com/17431299/74637307-0de95480-516a-11ea-9aa2-3e9acbc2a53c.png)
